export const LOGIN = 'LOGIN';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';

export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';

export const ANOTHER_ACTION = 'ANOTHER_ACTION';

